### ISSUE TITLE
Exception thrown when column is invisible and row got removed and immediately draw() called

### ISSUE THREAD

**Issue by AndOne1974** [DataTables/DataTablesSrc#266] opened 2024-03-25 14:57 UTC
https://github.com/DataTables/DataTablesSrc/blame/0e78039c4ae0e473be363a87ceecce74b0d4673c/js/core/core.internal.js#L159

If a[ order[i] ] is null than an exception is thrown. This can happen if serverSide rendering = true, the column is invisible and the row got removed by rows(.selected").remove().draw().

fix:

if ( a[ order[i] ] && a[ order[i] ][ prop ] ) {
	out.push( a[ order[i] ][ prop ][ prop2 ] );
}

should be the same if() as in _pluck

**Comment by AllanJard** [comment] 2024-03-25 15:02
Hi - thanks for this!

```
rows(.selected").remove().draw().
```

If you are using server-side processing, you wouldn't typically use `rows().remove()` since that is a client-side action. It has no effect on the server-side data.

Are you able to give me a link to a page showing the issue please?

**Comment by AndOne1974** [comment] 2024-03-25 15:06
Well i call it on the client side to remove the row immediately and afterwards i do an ajax call to remove the record in the db.

**Comment by AndOne1974** [comment] 2024-03-25 15:10
btw the remove() set the record in hashmap to null but the draw() failed with an exception. It has nothing to do with the serverside, it is simply a client side issue if the column is not visible. You cannot  check for prop2 if a[ order[i] ] is undefined.

**Comment by AllanJard** [comment] 2024-03-25 15:14
Can you give me a link to a test case showing the issue so I can add it to the unit tests please? There is something more going on than just a cell in a hidden column and a row being removed, as that works fine as shown here: https://live.datatables.net/xixawalo/1/edit .

**Comment by AllanJard** [comment] 2024-03-25 15:14
Oops - didn't mean to close this before. pressed the wrong button!

**Comment by AndOne1974** [comment] 2024-03-25 15:17
you need serverSide set ti true, that shoud trigger an other draw() code

**Comment by AndOne1974** [comment] 2024-03-25 15:18
VM53532 datatables.js:86694 
 Uncaught TypeError: Cannot read properties of null (reading 'anCells')
    at _pluck_order (VM53532 datatables.js:86694:23)
    at _Api.<anonymous> (VM53532 datatables.js:93921:11)
    at _Api.iterator (VM53532 datatables.js:92189:17)
    at _Api.<anonymous> (VM53532 datatables.js:93920:15)
    at _Api.<anonymous> (VM53532 datatables.js:92403:18)
    at _Api.nodes (VM53532 datatables.js:92279:17)
    at Responsive._setColumnVis (VM53532 datatables.js:106645:5)
    at Boolean.<anonymous> (VM53532 datatables.js:105632:11)
    at Function.each (VM53403 jquery.js:383:20)
    at HTMLTableElement.<anonymous> (VM53532 datatables.js:105630:6)

**Comment by AndOne1974** [comment] 2024-03-25 15:18
* Included libraries:
 *   JSZip 3.10.1, pdfmake 0.2.7, DataTables 2.0.3, Buttons 3.0.1, Column visibility 3.0.1, HTML5 export 3.0.1, Print view 3.0.1, FixedHeader 4.0.1, Responsive 3.0.0, Select 2.0.0

**Comment by AndOne1974** [comment] 2024-03-25 15:21
![image](https://github.com/DataTables/DataTablesSrc/assets/1571332/78d9f134-e7dd-427c-9222-5f29482554ff)

**Comment by AndOne1974** [comment] 2024-03-27 13:10
@AllanJard do you need more info about the error?

**Comment by AllanJard** [comment] 2024-03-27 16:16
Thank you for the example! Based on that, here is a way to reproduce it without the extensions: https://live.datatables.net/nisokizi/23/edit .

I think it is [this block](https://github.com/DataTables/DataTablesSrc/blob/28687ae08e66cc22912be93524d7f08840c55376/js/api/api.selectors.js#L103-L111) that is the error rather than the `pluck` function. I'll write a test and check it out.

**Comment by AllanJard** [comment] 2024-03-27 16:29
I've [committed this fix](https://github.com/DataTables/DataTablesSrc/commit/b1e2e0c853ad02f3027202c2fb662ff317bce7dd) for that. I think the server-side processing "optimisation" could actually lead to a whole load of similar bugs. Per the comment there, I don't really expect client-side operations like this when using server-side processing, but it removes code to fix it, so that seems good to me :)

**Closed** 2024-03-27 16:29 UTC

**Comment by AndOne1974** [comment] 2024-03-27 18:16
Thx @AllanJard !
