### ISSUE TITLE
Ajax sourced data - handling success response (status: 200) with empty collections

### ISSUE THREAD

**Issue by hnhegde** [DataTables/DataTablesSrc#158] opened 2020-03-18 06:45 UTC
When a GET request is made to a Restful API that returns a 200 - OK, but has no data to offer and hence returns an empty collection ({} or []), following error is thrown by DataTables:
```
jquery.dataTables.js:4745 Uncaught TypeError: Cannot read property 'length' of undefined
    at jquery.dataTables.js:4745
    at callback (jquery.dataTables.js:3865)
    at Object.success (jquery.dataTables.js:3895)
    at fire (jquery.js:3291)
    at Object.fireWith [as resolveWith] (jquery.js:3421)
    at done (jquery.js:9533)
    at XMLHttpRequest.<anonymous> (jquery.js:9785)
```

Tracing inside the jquery.dataTables.js:
```
 4739                         // if there is an ajax source load the data
 4740                         if ( dataSrc == 'ajax' ) {
 4741                                 _fnBuildAjax( settings, [], function(json) {
 4742                                         var aData = _fnAjaxDataSrc( settings, json );
 4743 
 4744                                         // Got the data - add it to the table
 4745                                         for ( i=0 ; i<aData.length ; i++ ) {
 4746                                                 _fnAddData( settings, aData[i] );
 4747                                         }
 4748 
 4749                                         // Reset the init display for cookie saving. We've already done
 4750                                         // a filter, and therefore cleared it before. So we need to make
 4751                                         // it appear 'fresh'
 4752                                         settings.iInitDisplayStart = iAjaxStart;
 4753 
 4754                                         _fnReDraw( settings );
 4755 
 4756                                         _fnProcessingDisplay( settings, false );
 4757                                         _fnInitComplete( settings, json );
 4758                                 }, settings );
 4759                         }
```

At line 4745, it appears that a check for existence of rows in the returned dataset is required, prior to iterating over them.

I am using version 1.10.20. 

Kindly review. I would be happy to submit a PR.

**Comment by DataTables** [comment] 2020-03-18 09:50
Thanks for posting this. I've actually committed a similar change for the v2 branch (hoping to get that released later this year). As such I'll close this for the moment - it isn't a change I want to make in 1.x since it is working as designed for that series. As I say, it will change for 2.x.

**Closed by DataTables** 2020-03-18 09:50 UTC

**Comment by hnhegde** [comment] 2020-03-18 11:59
Excellent!

--
Best Regards,
Harsha N Hegde
